namespace TDF.Net
{
    partial class loginForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(loginForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.passwordLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.departmentDropdown = new Bunifu.UI.WinForms.BunifuDropdown();
            this.departmentLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.panel = new System.Windows.Forms.Panel();
            this.controlBox = new Bunifu.UI.WinForms.BunifuFormControlBox();
            this.updateButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.signupButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.loginButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtUsername = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.nameLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.nameTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.titleLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.titlesDropdown = new Bunifu.UI.WinForms.BunifuDropdown();
            this.guiDropdown = new Bunifu.UI.WinForms.BunifuDropdown();
            this.guiLabel = new Bunifu.UI.WinForms.BunifuLabel();
            this.panel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // passwordLabel
            // 
            this.passwordLabel.AllowParentOverrides = false;
            this.passwordLabel.AutoEllipsis = false;
            this.passwordLabel.CursorType = null;
            this.passwordLabel.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.passwordLabel.Location = new System.Drawing.Point(26, 134);
            this.passwordLabel.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.passwordLabel.Name = "passwordLabel";
            this.passwordLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.passwordLabel.Size = new System.Drawing.Size(80, 25);
            this.passwordLabel.TabIndex = 2;
            this.passwordLabel.Text = "Password:";
            this.passwordLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.passwordLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.bunifuLabel1.Location = new System.Drawing.Point(23, 76);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(83, 25);
            this.bunifuLabel1.TabIndex = 12;
            this.bunifuLabel1.Text = "Username:";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // departmentDropdown
            // 
            this.departmentDropdown.BackColor = System.Drawing.Color.Transparent;
            this.departmentDropdown.BackgroundColor = System.Drawing.Color.White;
            this.departmentDropdown.BorderColor = System.Drawing.Color.Silver;
            this.departmentDropdown.BorderRadius = 1;
            this.departmentDropdown.Color = System.Drawing.Color.Silver;
            this.departmentDropdown.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.departmentDropdown.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.departmentDropdown.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.departmentDropdown.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.departmentDropdown.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.departmentDropdown.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.departmentDropdown.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.departmentDropdown.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.departmentDropdown.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.departmentDropdown.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.departmentDropdown.FillDropDown = true;
            this.departmentDropdown.FillIndicator = false;
            this.departmentDropdown.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.departmentDropdown.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.departmentDropdown.ForeColor = System.Drawing.Color.Black;
            this.departmentDropdown.FormattingEnabled = true;
            this.departmentDropdown.Icon = null;
            this.departmentDropdown.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.departmentDropdown.IndicatorColor = System.Drawing.Color.DarkGray;
            this.departmentDropdown.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.departmentDropdown.IndicatorThickness = 2;
            this.departmentDropdown.IsDropdownOpened = false;
            this.departmentDropdown.ItemBackColor = System.Drawing.Color.White;
            this.departmentDropdown.ItemBorderColor = System.Drawing.Color.White;
            this.departmentDropdown.ItemForeColor = System.Drawing.Color.Black;
            this.departmentDropdown.ItemHeight = 26;
            this.departmentDropdown.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.departmentDropdown.ItemHighLightForeColor = System.Drawing.Color.White;
            this.departmentDropdown.ItemTopMargin = 3;
            this.departmentDropdown.Location = new System.Drawing.Point(144, 241);
            this.departmentDropdown.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.departmentDropdown.Name = "departmentDropdown";
            this.departmentDropdown.Size = new System.Drawing.Size(303, 32);
            this.departmentDropdown.TabIndex = 13;
            this.departmentDropdown.Text = null;
            this.departmentDropdown.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.departmentDropdown.TextLeftMargin = 5;
            this.departmentDropdown.Visible = false;
            this.departmentDropdown.SelectedIndexChanged += new System.EventHandler(this.departmentDropdown_SelectedIndexChanged);
            // 
            // departmentLabel
            // 
            this.departmentLabel.AllowParentOverrides = false;
            this.departmentLabel.AutoEllipsis = false;
            this.departmentLabel.CursorType = null;
            this.departmentLabel.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.departmentLabel.Location = new System.Drawing.Point(15, 245);
            this.departmentLabel.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.departmentLabel.Name = "departmentLabel";
            this.departmentLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.departmentLabel.Size = new System.Drawing.Size(99, 25);
            this.departmentLabel.TabIndex = 14;
            this.departmentLabel.Text = "Department:";
            this.departmentLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.departmentLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.departmentLabel.Visible = false;
            // 
            // panel
            // 
            this.panel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(150)))), ((int)(((byte)(136)))));
            this.panel.Controls.Add(this.controlBox);
            this.panel.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel.Location = new System.Drawing.Point(0, 0);
            this.panel.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.panel.Name = "panel";
            this.panel.Size = new System.Drawing.Size(1217, 50);
            this.panel.TabIndex = 23;
            this.panel.Paint += new System.Windows.Forms.PaintEventHandler(this.panel_Paint);
            this.panel.MouseDown += new System.Windows.Forms.MouseEventHandler(this.panel_MouseDown);
            // 
            // controlBox
            // 
            this.controlBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.controlBox.BunifuFormDrag = null;
            this.controlBox.CloseBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.controlBox.CloseBoxOptions.BorderRadius = 0;
            this.controlBox.CloseBoxOptions.Enabled = true;
            this.controlBox.CloseBoxOptions.EnableDefaultAction = true;
            this.controlBox.CloseBoxOptions.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.controlBox.CloseBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("controlBox.CloseBoxOptions.Icon")));
            this.controlBox.CloseBoxOptions.IconAlt = null;
            this.controlBox.CloseBoxOptions.IconColor = System.Drawing.Color.White;
            this.controlBox.CloseBoxOptions.IconHoverColor = System.Drawing.Color.White;
            this.controlBox.CloseBoxOptions.IconPressedColor = System.Drawing.Color.White;
            this.controlBox.CloseBoxOptions.IconSize = new System.Drawing.Size(18, 18);
            this.controlBox.CloseBoxOptions.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.controlBox.ForeColor = System.Drawing.Color.White;
            this.controlBox.HelpBox = false;
            this.controlBox.HelpBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.controlBox.HelpBoxOptions.BorderRadius = 0;
            this.controlBox.HelpBoxOptions.Enabled = true;
            this.controlBox.HelpBoxOptions.EnableDefaultAction = true;
            this.controlBox.HelpBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.controlBox.HelpBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("controlBox.HelpBoxOptions.Icon")));
            this.controlBox.HelpBoxOptions.IconAlt = null;
            this.controlBox.HelpBoxOptions.IconColor = System.Drawing.Color.Black;
            this.controlBox.HelpBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.controlBox.HelpBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.controlBox.HelpBoxOptions.IconSize = new System.Drawing.Size(22, 22);
            this.controlBox.HelpBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.controlBox.Location = new System.Drawing.Point(1028, 2);
            this.controlBox.Margin = new System.Windows.Forms.Padding(2);
            this.controlBox.MaximizeBox = false;
            this.controlBox.MaximizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.controlBox.MaximizeBoxOptions.BorderRadius = 0;
            this.controlBox.MaximizeBoxOptions.Enabled = true;
            this.controlBox.MaximizeBoxOptions.EnableDefaultAction = true;
            this.controlBox.MaximizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.controlBox.MaximizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("controlBox.MaximizeBoxOptions.Icon")));
            this.controlBox.MaximizeBoxOptions.IconAlt = ((System.Drawing.Image)(resources.GetObject("controlBox.MaximizeBoxOptions.IconAlt")));
            this.controlBox.MaximizeBoxOptions.IconColor = System.Drawing.Color.White;
            this.controlBox.MaximizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.controlBox.MaximizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.controlBox.MaximizeBoxOptions.IconSize = new System.Drawing.Size(16, 16);
            this.controlBox.MaximizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.controlBox.MinimizeBox = true;
            this.controlBox.MinimizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.controlBox.MinimizeBoxOptions.BorderRadius = 0;
            this.controlBox.MinimizeBoxOptions.Enabled = true;
            this.controlBox.MinimizeBoxOptions.EnableDefaultAction = true;
            this.controlBox.MinimizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.controlBox.MinimizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("controlBox.MinimizeBoxOptions.Icon")));
            this.controlBox.MinimizeBoxOptions.IconAlt = null;
            this.controlBox.MinimizeBoxOptions.IconColor = System.Drawing.Color.White;
            this.controlBox.MinimizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.controlBox.MinimizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.controlBox.MinimizeBoxOptions.IconSize = new System.Drawing.Size(14, 14);
            this.controlBox.MinimizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.controlBox.Name = "controlBox";
            this.controlBox.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.controlBox.ShowDesignBorders = false;
            this.controlBox.Size = new System.Drawing.Size(187, 46);
            this.controlBox.TabIndex = 19;
            // 
            // updateButton
            // 
            this.updateButton.AllowAnimations = true;
            this.updateButton.AllowMouseEffects = true;
            this.updateButton.AllowToggling = false;
            this.updateButton.AnimationSpeed = 200;
            this.updateButton.AutoGenerateColors = true;
            this.updateButton.AutoRoundBorders = false;
            this.updateButton.AutoSizeLeftIcon = true;
            this.updateButton.AutoSizeRightIcon = true;
            this.updateButton.BackColor = System.Drawing.Color.Transparent;
            this.updateButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.updateButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("updateButton.BackgroundImage")));
            this.updateButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.ButtonText = "Change password";
            this.updateButton.ButtonTextMarginLeft = 0;
            this.updateButton.ColorContrastOnClick = 45;
            this.updateButton.ColorContrastOnHover = 45;
            this.updateButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.updateButton.CustomizableEdges = borderEdges7;
            this.updateButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.updateButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.updateButton.DisabledFillColor = System.Drawing.Color.Empty;
            this.updateButton.DisabledForecolor = System.Drawing.Color.Empty;
            this.updateButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.updateButton.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.updateButton.ForeColor = System.Drawing.Color.White;
            this.updateButton.IconLeft = null;
            this.updateButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.updateButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.updateButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.updateButton.IconMarginLeft = 11;
            this.updateButton.IconPadding = 10;
            this.updateButton.IconRight = null;
            this.updateButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.updateButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.updateButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.updateButton.IconSize = 25;
            this.updateButton.IdleBorderColor = System.Drawing.Color.Empty;
            this.updateButton.IdleBorderRadius = 0;
            this.updateButton.IdleBorderThickness = 0;
            this.updateButton.IdleFillColor = System.Drawing.Color.Empty;
            this.updateButton.IdleIconLeftImage = null;
            this.updateButton.IdleIconRightImage = null;
            this.updateButton.IndicateFocus = false;
            this.updateButton.Location = new System.Drawing.Point(144, 479);
            this.updateButton.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.updateButton.Name = "updateButton";
            this.updateButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.updateButton.OnDisabledState.BorderRadius = 1;
            this.updateButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.OnDisabledState.BorderThickness = 1;
            this.updateButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.updateButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.updateButton.OnDisabledState.IconLeftImage = null;
            this.updateButton.OnDisabledState.IconRightImage = null;
            this.updateButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            this.updateButton.onHoverState.BorderRadius = 1;
            this.updateButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.onHoverState.BorderThickness = 1;
            this.updateButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(131)))), ((int)(((byte)(193)))), ((int)(((byte)(255)))));
            this.updateButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.updateButton.onHoverState.IconLeftImage = null;
            this.updateButton.onHoverState.IconRightImage = null;
            this.updateButton.OnIdleState.BorderColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.updateButton.OnIdleState.BorderRadius = 1;
            this.updateButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.OnIdleState.BorderThickness = 1;
            this.updateButton.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.updateButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.updateButton.OnIdleState.IconLeftImage = null;
            this.updateButton.OnIdleState.IconRightImage = null;
            this.updateButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.updateButton.OnPressedState.BorderRadius = 1;
            this.updateButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateButton.OnPressedState.BorderThickness = 1;
            this.updateButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(79)))), ((int)(((byte)(140)))));
            this.updateButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.updateButton.OnPressedState.IconLeftImage = null;
            this.updateButton.OnPressedState.IconRightImage = null;
            this.updateButton.Size = new System.Drawing.Size(246, 36);
            this.updateButton.TabIndex = 11;
            this.updateButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.updateButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.updateButton.TextMarginLeft = 0;
            this.updateButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.updateButton.UseDefaultRadiusAndThickness = true;
            this.updateButton.Click += new System.EventHandler(this.updateButton_Click);
            // 
            // signupButton
            // 
            this.signupButton.AllowAnimations = true;
            this.signupButton.AllowMouseEffects = true;
            this.signupButton.AllowToggling = false;
            this.signupButton.AnimationSpeed = 200;
            this.signupButton.AutoGenerateColors = true;
            this.signupButton.AutoRoundBorders = false;
            this.signupButton.AutoSizeLeftIcon = true;
            this.signupButton.AutoSizeRightIcon = true;
            this.signupButton.BackColor = System.Drawing.Color.Transparent;
            this.signupButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.signupButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("signupButton.BackgroundImage")));
            this.signupButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.signupButton.ButtonText = "Sign Up";
            this.signupButton.ButtonTextMarginLeft = 0;
            this.signupButton.ColorContrastOnClick = 45;
            this.signupButton.ColorContrastOnHover = 45;
            this.signupButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.signupButton.CustomizableEdges = borderEdges8;
            this.signupButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.signupButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.signupButton.DisabledFillColor = System.Drawing.Color.Empty;
            this.signupButton.DisabledForecolor = System.Drawing.Color.Empty;
            this.signupButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.signupButton.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.signupButton.ForeColor = System.Drawing.Color.White;
            this.signupButton.IconLeft = null;
            this.signupButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.signupButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.signupButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.signupButton.IconMarginLeft = 11;
            this.signupButton.IconPadding = 10;
            this.signupButton.IconRight = null;
            this.signupButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.signupButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.signupButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.signupButton.IconSize = 25;
            this.signupButton.IdleBorderColor = System.Drawing.Color.Empty;
            this.signupButton.IdleBorderRadius = 0;
            this.signupButton.IdleBorderThickness = 0;
            this.signupButton.IdleFillColor = System.Drawing.Color.Empty;
            this.signupButton.IdleIconLeftImage = null;
            this.signupButton.IdleIconRightImage = null;
            this.signupButton.IndicateFocus = false;
            this.signupButton.Location = new System.Drawing.Point(195, 414);
            this.signupButton.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.signupButton.Name = "signupButton";
            this.signupButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.signupButton.OnDisabledState.BorderRadius = 1;
            this.signupButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.signupButton.OnDisabledState.BorderThickness = 1;
            this.signupButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.signupButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.signupButton.OnDisabledState.IconLeftImage = null;
            this.signupButton.OnDisabledState.IconRightImage = null;
            this.signupButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            this.signupButton.onHoverState.BorderRadius = 1;
            this.signupButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.signupButton.onHoverState.BorderThickness = 1;
            this.signupButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(131)))), ((int)(((byte)(193)))), ((int)(((byte)(255)))));
            this.signupButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.signupButton.onHoverState.IconLeftImage = null;
            this.signupButton.onHoverState.IconRightImage = null;
            this.signupButton.OnIdleState.BorderColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.signupButton.OnIdleState.BorderRadius = 1;
            this.signupButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.signupButton.OnIdleState.BorderThickness = 1;
            this.signupButton.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.signupButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.signupButton.OnIdleState.IconLeftImage = null;
            this.signupButton.OnIdleState.IconRightImage = null;
            this.signupButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.signupButton.OnPressedState.BorderRadius = 1;
            this.signupButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.signupButton.OnPressedState.BorderThickness = 1;
            this.signupButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(79)))), ((int)(((byte)(140)))));
            this.signupButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.signupButton.OnPressedState.IconLeftImage = null;
            this.signupButton.OnPressedState.IconRightImage = null;
            this.signupButton.Size = new System.Drawing.Size(144, 36);
            this.signupButton.TabIndex = 8;
            this.signupButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.signupButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.signupButton.TextMarginLeft = 0;
            this.signupButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.signupButton.UseDefaultRadiusAndThickness = true;
            this.signupButton.Click += new System.EventHandler(this.signupButton_Click);
            // 
            // loginButton
            // 
            this.loginButton.AllowAnimations = true;
            this.loginButton.AllowMouseEffects = true;
            this.loginButton.AllowToggling = false;
            this.loginButton.AnimationSpeed = 200;
            this.loginButton.AutoGenerateColors = true;
            this.loginButton.AutoRoundBorders = false;
            this.loginButton.AutoSizeLeftIcon = true;
            this.loginButton.AutoSizeRightIcon = true;
            this.loginButton.BackColor = System.Drawing.Color.Transparent;
            this.loginButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.loginButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("loginButton.BackgroundImage")));
            this.loginButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.loginButton.ButtonText = "Log In";
            this.loginButton.ButtonTextMarginLeft = 0;
            this.loginButton.ColorContrastOnClick = 45;
            this.loginButton.ColorContrastOnHover = 45;
            this.loginButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.loginButton.CustomizableEdges = borderEdges9;
            this.loginButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.loginButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.loginButton.DisabledFillColor = System.Drawing.Color.Empty;
            this.loginButton.DisabledForecolor = System.Drawing.Color.Empty;
            this.loginButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.loginButton.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.loginButton.ForeColor = System.Drawing.Color.White;
            this.loginButton.IconLeft = null;
            this.loginButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.loginButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.loginButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.loginButton.IconMarginLeft = 11;
            this.loginButton.IconPadding = 10;
            this.loginButton.IconRight = null;
            this.loginButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.loginButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.loginButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.loginButton.IconSize = 25;
            this.loginButton.IdleBorderColor = System.Drawing.Color.Empty;
            this.loginButton.IdleBorderRadius = 0;
            this.loginButton.IdleBorderThickness = 0;
            this.loginButton.IdleFillColor = System.Drawing.Color.Empty;
            this.loginButton.IdleIconLeftImage = null;
            this.loginButton.IdleIconRightImage = null;
            this.loginButton.IndicateFocus = false;
            this.loginButton.Location = new System.Drawing.Point(195, 347);
            this.loginButton.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.loginButton.Name = "loginButton";
            this.loginButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.loginButton.OnDisabledState.BorderRadius = 1;
            this.loginButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.loginButton.OnDisabledState.BorderThickness = 1;
            this.loginButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.loginButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.loginButton.OnDisabledState.IconLeftImage = null;
            this.loginButton.OnDisabledState.IconRightImage = null;
            this.loginButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            this.loginButton.onHoverState.BorderRadius = 1;
            this.loginButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.loginButton.onHoverState.BorderThickness = 1;
            this.loginButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(131)))), ((int)(((byte)(193)))), ((int)(((byte)(255)))));
            this.loginButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.loginButton.onHoverState.IconLeftImage = null;
            this.loginButton.onHoverState.IconRightImage = null;
            this.loginButton.OnIdleState.BorderColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.loginButton.OnIdleState.BorderRadius = 1;
            this.loginButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.loginButton.OnIdleState.BorderThickness = 1;
            this.loginButton.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.loginButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.loginButton.OnIdleState.IconLeftImage = null;
            this.loginButton.OnIdleState.IconRightImage = null;
            this.loginButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.loginButton.OnPressedState.BorderRadius = 1;
            this.loginButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.loginButton.OnPressedState.BorderThickness = 1;
            this.loginButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(79)))), ((int)(((byte)(140)))));
            this.loginButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.loginButton.OnPressedState.IconLeftImage = null;
            this.loginButton.OnPressedState.IconRightImage = null;
            this.loginButton.Size = new System.Drawing.Size(144, 36);
            this.loginButton.TabIndex = 7;
            this.loginButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.loginButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.loginButton.TextMarginLeft = 0;
            this.loginButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.loginButton.UseDefaultRadiusAndThickness = true;
            this.loginButton.Click += new System.EventHandler(this.loginButton_Click);
            // 
            // txtPassword
            // 
            this.txtPassword.AcceptsReturn = false;
            this.txtPassword.AcceptsTab = false;
            this.txtPassword.AnimationSpeed = 200;
            this.txtPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPassword.AutoSizeHeight = true;
            this.txtPassword.BackColor = System.Drawing.Color.Transparent;
            this.txtPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPassword.BackgroundImage")));
            this.txtPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPassword.BorderRadius = 1;
            this.txtPassword.BorderThickness = 1;
            this.txtPassword.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPassword.DefaultText = "";
            this.txtPassword.FillColor = System.Drawing.Color.White;
            this.txtPassword.HideSelection = true;
            this.txtPassword.IconLeft = null;
            this.txtPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.IconPadding = 10;
            this.txtPassword.IconRight = null;
            this.txtPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.Lines = new string[0];
            this.txtPassword.Location = new System.Drawing.Point(145, 130);
            this.txtPassword.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtPassword.MaxLength = 32767;
            this.txtPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPassword.Modified = false;
            this.txtPassword.Multiline = false;
            this.txtPassword.Name = "txtPassword";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPassword.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnIdleState = stateProperties28;
            this.txtPassword.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtPassword.PasswordChar = '*';
            this.txtPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPassword.PlaceholderText = "";
            this.txtPassword.ReadOnly = false;
            this.txtPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPassword.SelectedText = "";
            this.txtPassword.SelectionLength = 0;
            this.txtPassword.SelectionStart = 0;
            this.txtPassword.ShortcutsEnabled = true;
            this.txtPassword.Size = new System.Drawing.Size(303, 36);
            this.txtPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPassword.TabIndex = 4;
            this.txtPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPassword.TextMarginBottom = 0;
            this.txtPassword.TextMarginLeft = 3;
            this.txtPassword.TextMarginTop = 1;
            this.txtPassword.TextPlaceholder = "";
            this.txtPassword.UseSystemPasswordChar = true;
            this.txtPassword.WordWrap = true;
            this.txtPassword.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtPassword_KeyDown);
            // 
            // txtUsername
            // 
            this.txtUsername.AcceptsReturn = false;
            this.txtUsername.AcceptsTab = false;
            this.txtUsername.AnimationSpeed = 200;
            this.txtUsername.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUsername.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUsername.AutoSizeHeight = true;
            this.txtUsername.BackColor = System.Drawing.Color.Transparent;
            this.txtUsername.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUsername.BackgroundImage")));
            this.txtUsername.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUsername.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUsername.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUsername.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUsername.BorderRadius = 1;
            this.txtUsername.BorderThickness = 1;
            this.txtUsername.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtUsername.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUsername.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsername.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtUsername.DefaultText = "";
            this.txtUsername.FillColor = System.Drawing.Color.White;
            this.txtUsername.HideSelection = true;
            this.txtUsername.IconLeft = null;
            this.txtUsername.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsername.IconPadding = 10;
            this.txtUsername.IconRight = null;
            this.txtUsername.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUsername.Lines = new string[0];
            this.txtUsername.Location = new System.Drawing.Point(145, 75);
            this.txtUsername.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtUsername.MaxLength = 32767;
            this.txtUsername.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUsername.Modified = false;
            this.txtUsername.Multiline = false;
            this.txtUsername.Name = "txtUsername";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsername.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUsername.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsername.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUsername.OnIdleState = stateProperties32;
            this.txtUsername.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtUsername.PasswordChar = '\0';
            this.txtUsername.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtUsername.PlaceholderText = "";
            this.txtUsername.ReadOnly = false;
            this.txtUsername.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUsername.SelectedText = "";
            this.txtUsername.SelectionLength = 0;
            this.txtUsername.SelectionStart = 0;
            this.txtUsername.ShortcutsEnabled = true;
            this.txtUsername.Size = new System.Drawing.Size(303, 36);
            this.txtUsername.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUsername.TabIndex = 3;
            this.txtUsername.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUsername.TextMarginBottom = 0;
            this.txtUsername.TextMarginLeft = 3;
            this.txtUsername.TextMarginTop = 1;
            this.txtUsername.TextPlaceholder = "";
            this.txtUsername.UseSystemPasswordChar = false;
            this.txtUsername.WordWrap = true;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = global::TDF.Properties.Resources.team;
            this.pictureBox1.Location = new System.Drawing.Point(499, 58);
            this.pictureBox1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(709, 482);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 24;
            this.pictureBox1.TabStop = false;
            // 
            // nameLabel
            // 
            this.nameLabel.AllowParentOverrides = false;
            this.nameLabel.AutoEllipsis = false;
            this.nameLabel.CursorType = null;
            this.nameLabel.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.nameLabel.Location = new System.Drawing.Point(23, 192);
            this.nameLabel.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.nameLabel.Name = "nameLabel";
            this.nameLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.nameLabel.Size = new System.Drawing.Size(83, 25);
            this.nameLabel.TabIndex = 9;
            this.nameLabel.Text = "Full Name:";
            this.nameLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.nameLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.nameLabel.Visible = false;
            // 
            // nameTextBox
            // 
            this.nameTextBox.AcceptsReturn = false;
            this.nameTextBox.AcceptsTab = false;
            this.nameTextBox.AnimationSpeed = 200;
            this.nameTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nameTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nameTextBox.AutoSizeHeight = true;
            this.nameTextBox.BackColor = System.Drawing.Color.Transparent;
            this.nameTextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nameTextBox.BackgroundImage")));
            this.nameTextBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.nameTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nameTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nameTextBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.nameTextBox.BorderRadius = 1;
            this.nameTextBox.BorderThickness = 1;
            this.nameTextBox.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.nameTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nameTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nameTextBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.nameTextBox.DefaultText = "";
            this.nameTextBox.FillColor = System.Drawing.Color.White;
            this.nameTextBox.HideSelection = true;
            this.nameTextBox.IconLeft = null;
            this.nameTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameTextBox.IconPadding = 10;
            this.nameTextBox.IconRight = null;
            this.nameTextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameTextBox.Lines = new string[0];
            this.nameTextBox.Location = new System.Drawing.Point(145, 188);
            this.nameTextBox.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.nameTextBox.MaxLength = 32767;
            this.nameTextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.nameTextBox.Modified = false;
            this.nameTextBox.Multiline = false;
            this.nameTextBox.Name = "nameTextBox";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameTextBox.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nameTextBox.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameTextBox.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameTextBox.OnIdleState = stateProperties36;
            this.nameTextBox.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.nameTextBox.PasswordChar = '\0';
            this.nameTextBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.nameTextBox.PlaceholderText = "";
            this.nameTextBox.ReadOnly = false;
            this.nameTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nameTextBox.SelectedText = "";
            this.nameTextBox.SelectionLength = 0;
            this.nameTextBox.SelectionStart = 0;
            this.nameTextBox.ShortcutsEnabled = true;
            this.nameTextBox.Size = new System.Drawing.Size(303, 36);
            this.nameTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.nameTextBox.TabIndex = 10;
            this.nameTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nameTextBox.TextMarginBottom = 0;
            this.nameTextBox.TextMarginLeft = 3;
            this.nameTextBox.TextMarginTop = 1;
            this.nameTextBox.TextPlaceholder = "";
            this.nameTextBox.UseSystemPasswordChar = false;
            this.nameTextBox.Visible = false;
            this.nameTextBox.WordWrap = true;
            // 
            // titleLabel
            // 
            this.titleLabel.AllowParentOverrides = false;
            this.titleLabel.AutoEllipsis = false;
            this.titleLabel.CursorType = null;
            this.titleLabel.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.titleLabel.Location = new System.Drawing.Point(72, 309);
            this.titleLabel.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.titleLabel.Name = "titleLabel";
            this.titleLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.titleLabel.Size = new System.Drawing.Size(36, 25);
            this.titleLabel.TabIndex = 26;
            this.titleLabel.Text = "Title:";
            this.titleLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.titleLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.titleLabel.Visible = false;
            // 
            // titlesDropdown
            // 
            this.titlesDropdown.BackColor = System.Drawing.Color.Transparent;
            this.titlesDropdown.BackgroundColor = System.Drawing.Color.White;
            this.titlesDropdown.BorderColor = System.Drawing.Color.Silver;
            this.titlesDropdown.BorderRadius = 1;
            this.titlesDropdown.Color = System.Drawing.Color.Silver;
            this.titlesDropdown.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.titlesDropdown.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.titlesDropdown.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.titlesDropdown.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.titlesDropdown.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.titlesDropdown.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.titlesDropdown.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.titlesDropdown.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.titlesDropdown.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.titlesDropdown.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.titlesDropdown.FillDropDown = true;
            this.titlesDropdown.FillIndicator = false;
            this.titlesDropdown.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.titlesDropdown.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.titlesDropdown.ForeColor = System.Drawing.Color.Black;
            this.titlesDropdown.FormattingEnabled = true;
            this.titlesDropdown.Icon = null;
            this.titlesDropdown.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.titlesDropdown.IndicatorColor = System.Drawing.Color.DarkGray;
            this.titlesDropdown.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.titlesDropdown.IndicatorThickness = 2;
            this.titlesDropdown.IsDropdownOpened = false;
            this.titlesDropdown.ItemBackColor = System.Drawing.Color.White;
            this.titlesDropdown.ItemBorderColor = System.Drawing.Color.White;
            this.titlesDropdown.ItemForeColor = System.Drawing.Color.Black;
            this.titlesDropdown.ItemHeight = 26;
            this.titlesDropdown.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.titlesDropdown.ItemHighLightForeColor = System.Drawing.Color.White;
            this.titlesDropdown.ItemTopMargin = 3;
            this.titlesDropdown.Location = new System.Drawing.Point(145, 302);
            this.titlesDropdown.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.titlesDropdown.Name = "titlesDropdown";
            this.titlesDropdown.Size = new System.Drawing.Size(303, 32);
            this.titlesDropdown.TabIndex = 25;
            this.titlesDropdown.Text = null;
            this.titlesDropdown.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.titlesDropdown.TextLeftMargin = 5;
            this.titlesDropdown.Visible = false;
            // 
            // guiDropdown
            // 
            this.guiDropdown.BackColor = System.Drawing.Color.Transparent;
            this.guiDropdown.BackgroundColor = System.Drawing.Color.White;
            this.guiDropdown.BorderColor = System.Drawing.Color.Silver;
            this.guiDropdown.BorderRadius = 1;
            this.guiDropdown.Color = System.Drawing.Color.Silver;
            this.guiDropdown.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.guiDropdown.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.guiDropdown.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.guiDropdown.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.guiDropdown.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.guiDropdown.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.guiDropdown.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.guiDropdown.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.guiDropdown.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.guiDropdown.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Center;
            this.guiDropdown.FillDropDown = true;
            this.guiDropdown.FillIndicator = false;
            this.guiDropdown.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.guiDropdown.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.guiDropdown.ForeColor = System.Drawing.Color.Black;
            this.guiDropdown.FormattingEnabled = true;
            this.guiDropdown.Icon = null;
            this.guiDropdown.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.guiDropdown.IndicatorColor = System.Drawing.Color.DarkGray;
            this.guiDropdown.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.guiDropdown.IndicatorThickness = 2;
            this.guiDropdown.IsDropdownOpened = false;
            this.guiDropdown.ItemBackColor = System.Drawing.Color.White;
            this.guiDropdown.ItemBorderColor = System.Drawing.Color.White;
            this.guiDropdown.ItemForeColor = System.Drawing.Color.Black;
            this.guiDropdown.ItemHeight = 26;
            this.guiDropdown.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.guiDropdown.ItemHighLightForeColor = System.Drawing.Color.White;
            this.guiDropdown.Items.AddRange(new object[] {
            "Classic",
            "Modern"});
            this.guiDropdown.ItemTopMargin = 3;
            this.guiDropdown.Location = new System.Drawing.Point(195, 280);
            this.guiDropdown.Name = "guiDropdown";
            this.guiDropdown.Size = new System.Drawing.Size(144, 32);
            this.guiDropdown.TabIndex = 27;
            this.guiDropdown.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Center;
            this.guiDropdown.TextLeftMargin = 5;
            // 
            // guiLabel
            // 
            this.guiLabel.AllowParentOverrides = false;
            this.guiLabel.AutoEllipsis = false;
            this.guiLabel.CursorType = null;
            this.guiLabel.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.guiLabel.Location = new System.Drawing.Point(247, 247);
            this.guiLabel.Margin = new System.Windows.Forms.Padding(4);
            this.guiLabel.Name = "guiLabel";
            this.guiLabel.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.guiLabel.Size = new System.Drawing.Size(33, 25);
            this.guiLabel.TabIndex = 28;
            this.guiLabel.Text = "GUI:";
            this.guiLabel.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.guiLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // loginForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1217, 546);
            this.ControlBox = false;
            this.Controls.Add(this.guiLabel);
            this.Controls.Add(this.guiDropdown);
            this.Controls.Add(this.titleLabel);
            this.Controls.Add(this.titlesDropdown);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.updateButton);
            this.Controls.Add(this.signupButton);
            this.Controls.Add(this.loginButton);
            this.Controls.Add(this.panel);
            this.Controls.Add(this.departmentLabel);
            this.Controls.Add(this.departmentDropdown);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.nameTextBox);
            this.Controls.Add(this.nameLabel);
            this.Controls.Add(this.txtPassword);
            this.Controls.Add(this.txtUsername);
            this.Controls.Add(this.passwordLabel);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.MaximizeBox = false;
            this.Name = "loginForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Log In";
            this.Shown += new System.EventHandler(this.loginForm_Shown);
            this.panel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuLabel passwordLabel;
        private Bunifu.UI.WinForms.BunifuTextBox txtUsername;
        private Bunifu.UI.WinForms.BunifuTextBox txtPassword;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton loginButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton signupButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton updateButton;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuDropdown departmentDropdown;
        private Bunifu.UI.WinForms.BunifuLabel departmentLabel;
        private System.Windows.Forms.Panel panel;
        private Bunifu.UI.WinForms.BunifuFormControlBox controlBox;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel nameLabel;
        private Bunifu.UI.WinForms.BunifuTextBox nameTextBox;
        private Bunifu.UI.WinForms.BunifuLabel titleLabel;
        private Bunifu.UI.WinForms.BunifuDropdown titlesDropdown;
        private Bunifu.UI.WinForms.BunifuDropdown guiDropdown;
        private Bunifu.UI.WinForms.BunifuLabel guiLabel;
    }
}

